name: Flutter

on:
  pull_request:
    branches: [ "main" ]

jobs:
  flutter-check:
    name: 🐦 Flutter Check
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1
      - run: flutter --version

      - name: ⚙️ Install dependencies
        run: flutter pub get

      - name: 🔎 Analyze project source
        run: flutter analyze

      - name: 🧪 Run tests
        run: flutter test